[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"


ksp = "2.2.0-2.0.2"
pagingCompose = "3.3.6"
room = "2.8.3"
datastore = "1.1.7"
splashScreen = "1.0.1"
navVersion = "2.9.5"
kotlinSerialization = "1.9.0"
kotlinSerializationPlugin = "2.2.21"
timber = "5.0.1"
koinVersion = "4.1.1"
ktor = "3.3.1"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#paging compose
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }


#Koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinVersion" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinVersion" }


#Serialization
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }

#Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navVersion" }

#Room
room-compiler = {group = "androidx.room", name= "room-compiler", version.ref = "room"}
room-runtime = {group = "androidx.room", name ="room-runtime", version.ref = "room"}
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref="room"}
room-paging = {group = "androidx.room", name = "room-paging", version.ref = "room" }

#splash screen
splash-screen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }

#Ktor Client
ktorCore = { module = "io.ktor:ktor-client-core", name = "ktorCore", version.ref = "ktor" }
ktorLogging = { module = "io.ktor:ktor-client-logging", name = "ktorLogging", version.ref = "ktor" }
ktorContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", name = "ktorContentNegotiation", version.ref = "ktor" }
ktorSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json", name = "ktorSerialization", version.ref = "ktor" }
ktorOkHttp = { module = "io.ktor:ktor-client-okhttp", name = "ktorOkHttp", version.ref = "ktor"}
ktor-client-mock = {group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor"}

#datastore
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#timber logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPlugin" }


[bundles]
room = [
    "room-runtime",
    "room-ktx",
    "room-paging"
]
ktor-client = [
    "ktorCore",
    "ktorLogging",
    "ktorSerialization",
    "ktorOkHttp",
    "ktorContentNegotiation"]